const canvas=document.getElementById('gameCanvas');const ctx=canvas.getContext('2d');
const scoreText=document.getElementById('scoreText'),bestText=document.getElementById('bestText'),lifeText=document.getElementById('lifeText');
const startScreen=document.getElementById('startScreen'),gameOverScreen=document.getElementById('gameOverScreen');
const finalScore=document.getElementById('finalScore'),finalBest=document.getElementById('finalBest');
const startBtn=document.getElementById('startBtn'),restartBtn=document.getElementById('restartBtn'),fireBtn=document.getElementById('fireBtn');
const joy=document.getElementById('joystick'),stick=document.getElementById('stick');
let W,H,DPR;function resize(){DPR=Math.min(window.devicePixelRatio||1,2.5);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
let best=Number(localStorage.getItem('kozmoz_space_best')||0);bestText.textContent=best;
let player,bullets,meteors,stars,hearts,particles,score,lives,running,last,meteorTimer,heartTimer,difficulty,fireHeld,fireCd,joyVec={x:0,y:0};
function reset(){player={x:W*.18,y:H*.5,r:24,speed:5.2,inv:0};bullets=[];meteors=[];hearts=[];particles=[];stars=Array.from({length:140},()=>({x:Math.random()*W,y:Math.random()*H,z:Math.random()*2+0.5}));score=0;lives=3;difficulty=1;meteorTimer=0;heartTimer=0;fireHeld=false;fireCd=0;last=performance.now();running=true;updateHud();startScreen.classList.remove('active');gameOverScreen.classList.remove('active');requestAnimationFrame(loop)}
function updateHud(){scoreText.textContent=score;bestText.textContent=best;lifeText.textContent='❤️'.repeat(lives)}
function gameOver(){running=false;best=Math.max(best,score);localStorage.setItem('kozmoz_space_best',best);finalScore.textContent=score;finalBest.textContent=best;updateHud();gameOverScreen.classList.add('active')}
function shoot(){if(fireCd>0)return;fireCd=130;bullets.push({x:player.x+32,y:player.y-6,vx:12,r:5});bullets.push({x:player.x+32,y:player.y+6,vx:12,r:5});}
function spawnMeteor(){let big=Math.random()<.34;let r=big?rand(30,54):rand(15,28);meteors.push({x:W+r+20,y:rand(45,H-45),r,spd:rand(2.2,4.3)*difficulty,hp:big?3:1,rot:Math.random()*6,vr:rand(-.04,.04)})}
function spawnHeart(){hearts.push({x:W+30,y:rand(60,H-60),r:18,spd:3.2*difficulty,pulse:0})}
function rand(a,b){return Math.random()*(b-a)+a}
function loop(t){if(!running)return;let dt=Math.min(t-last,32);last=t;difficulty+=dt*0.000018;meteorTimer-=dt;heartTimer-=dt;fireCd-=dt;if(meteorTimer<=0){spawnMeteor();meteorTimer=Math.max(360,980-difficulty*150)}if(heartTimer<=0){if(Math.random()<.7)spawnHeart();heartTimer=rand(9000,15000)}if(fireHeld)shoot();update(dt);draw();requestAnimationFrame(loop)}
function update(dt){player.x+=joyVec.x*player.speed;player.y+=joyVec.y*player.speed;player.x=Math.max(35,Math.min(W*.55,player.x));player.y=Math.max(42,Math.min(H-42,player.y));if(player.inv>0)player.inv-=dt;
stars.forEach(s=>{s.x-=s.z*(1.7*difficulty);if(s.x<0){s.x=W;s.y=Math.random()*H}});bullets.forEach(b=>b.x+=b.vx);bullets=bullets.filter(b=>b.x<W+40);
meteors.forEach(m=>{m.x-=m.spd;m.rot+=m.vr});hearts.forEach(h=>{h.x-=h.spd;h.pulse+=.08});
for(let i=meteors.length-1;i>=0;i--){let m=meteors[i];for(let j=bullets.length-1;j>=0;j--){let b=bullets[j];if(dist(b,m)<m.r+b.r){bullets.splice(j,1);m.hp--;burst(b.x,b.y,8,'#ffb23f');if(m.hp<=0){score+=Math.round(m.r*2);burst(m.x,m.y,22,'#ff6b21');meteors.splice(i,1);updateHud()}break}}}
for(let i=meteors.length-1;i>=0;i--){let m=meteors[i];if(m.x<-80){meteors.splice(i,1);continue}if(player.inv<=0 && dist(player,m)<player.r+m.r*.75){meteors.splice(i,1);lives--;player.inv=1200;burst(player.x,player.y,35,'#35d7ff');updateHud();if(lives<=0){gameOver();return}}}
for(let i=hearts.length-1;i>=0;i--){let h=hearts[i];if(h.x<-50){hearts.splice(i,1);continue}if(dist(player,h)<player.r+h.r){hearts.splice(i,1);if(lives<3)lives++;score+=50;burst(h.x,h.y,24,'#ff3f6e');updateHud()}}
particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.life-=dt});particles=particles.filter(p=>p.life>0)}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function burst(x,y,n,c){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-4,4),vy:rand(-4,4),life:rand(280,700),c})}
function draw(){ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#05081d');g.addColorStop(.5,'#0b1b55');g.addColorStop(1,'#01020a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);stars.forEach(s=>{ctx.fillStyle=`rgba(255,255,255,${.35+s.z*.25})`;ctx.fillRect(s.x,s.y,s.z*1.4,s.z*1.4)});drawShip();bullets.forEach(drawBullet);meteors.forEach(drawMeteor);hearts.forEach(drawHeart);particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/700);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1})}
function drawShip(){ctx.save();ctx.translate(player.x,player.y);if(player.inv>0 && Math.floor(player.inv/100)%2===0)ctx.globalAlpha=.35;ctx.shadowColor='#31e7ff';ctx.shadowBlur=18;ctx.fillStyle='#dff8ff';ctx.beginPath();ctx.moveTo(34,0);ctx.lineTo(-22,-20);ctx.lineTo(-12,0);ctx.lineTo(-22,20);ctx.closePath();ctx.fill();ctx.fillStyle='#0aa6ff';ctx.beginPath();ctx.ellipse(-5,0,13,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff7b00';ctx.beginPath();ctx.moveTo(-24,-10);ctx.lineTo(-48,0);ctx.lineTo(-24,10);ctx.fill();ctx.restore()}
function drawBullet(b){ctx.shadowColor='#79f7ff';ctx.shadowBlur=18;ctx.fillStyle='#9dffff';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
function drawMeteor(m){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(m.rot);ctx.shadowColor='#ff6f26';ctx.shadowBlur=10;ctx.fillStyle=m.hp>1?'#8d5a43':'#705145';ctx.beginPath();for(let i=0;i<11;i++){let a=i/11*Math.PI*2;let rr=m.r*rand(.72,1.05);ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.fillStyle='rgba(255,255,255,.14)';ctx.beginPath();ctx.arc(-m.r*.25,-m.r*.2,m.r*.22,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawHeart(h){ctx.save();ctx.translate(h.x,h.y);let s=1+Math.sin(h.pulse)*.12;ctx.scale(s,s);ctx.shadowColor='#ff4d73';ctx.shadowBlur=18;ctx.fillStyle='#ff2d55';ctx.font='32px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('❤️',0,0);ctx.restore()}
function setJoy(clientX,clientY){let r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=clientX-cx,dy=clientY-cy,max=40,d=Math.hypot(dx,dy)||1,n=Math.min(max,d);joyVec={x:dx/d*(n/max),y:dy/d*(n/max)};stick.style.transform=`translate(${joyVec.x*40}px,${joyVec.y*40}px)`}
joy.addEventListener('touchstart',e=>{setJoy(e.touches[0].clientX,e.touches[0].clientY)},{passive:false});joy.addEventListener('touchmove',e=>{e.preventDefault();setJoy(e.touches[0].clientX,e.touches[0].clientY)},{passive:false});joy.addEventListener('touchend',()=>{joyVec={x:0,y:0};stick.style.transform='translate(0,0)'})
fireBtn.addEventListener('touchstart',e=>{e.preventDefault();fireHeld=true;shoot()},{passive:false});fireBtn.addEventListener('touchend',()=>fireHeld=false);fireBtn.addEventListener('mousedown',()=>{fireHeld=true;shoot()});fireBtn.addEventListener('mouseup',()=>fireHeld=false);
addEventListener('keydown',e=>{if(e.code==='Space')shoot();if(e.key==='ArrowUp'||e.key==='w')joyVec.y=-1;if(e.key==='ArrowDown'||e.key==='s')joyVec.y=1;if(e.key==='ArrowLeft'||e.key==='a')joyVec.x=-1;if(e.key==='ArrowRight'||e.key==='d')joyVec.x=1});addEventListener('keyup',e=>{if(['ArrowUp','ArrowDown','w','s'].includes(e.key))joyVec.y=0;if(['ArrowLeft','ArrowRight','a','d'].includes(e.key))joyVec.x=0});
startBtn.onclick=reset;restartBtn.onclick=reset;
